### ISSUE TITLE
Outdated documentation and compilation error with make 4.3/gcc 10

### ISSUE THREAD

**Issue by straw-son** [therealmuffin/synchronator#14] opened 2020-11-07 10:18 UTC
I'm trying to deal with some issues that prevent compilation of synchronator, but for now I'd just like to point out that the provided link to libconfig is going nowhere (http://www.hyperrealm.com/libconfig/libconfig-1.5.tar.gz).

(Are newer version of libconfig (1.7) supposed to work? That would narrow down the problem for me.)

Btw. thanks for this awesome program, I've been running it successfully to control a NAD C356BEE from a raspberry pi2 for some while now!

**Comment by therealmuffin** [comment] 2020-11-08 21:44
Good to hear Synchronator is working well for you (except for the compilation issues)!

It has been some time since I last compiled Synchronator (still running an embarrassingly old distro at the moment). I would be surprised if libconfig 1.7 would give any issues. I'll try to compile Synchronator in a recent Debian environment somewhere this month and update the documentation if necessary (including the faulty link).

What kind of issues do you encounter when compiling Synchronator?

**Comment by straw-son** [comment] 2020-11-09 10:32
Ok, so I'm trying to compile synchronator on a Raspberry Pi 4 running Arch Linux Arm 64 (aarch64).

Output of ./configure looks good:

    Configuring Synchronator
    ALSA found
    LIBCONFIG found
    CFLAGS:
    LDFLAGS: -lpthread -lm -lasound -lconfig
    Configure successful. You may now build with 'make'`

Here's the output of make (some error messages are in german):

    cc -c  synchronator.c -DINCLUDE_CONFIG
    synchronator.c: In Funktion »main«:
    synchronator.c:99:25: Warnung: Implizite Deklaration der Funktion »isprint« [-Wimplicit-function-declaration]
       99 |                 else if(isprint(optopt))
          |                         ^~~~~~~
    cc -c  volume.c -DINCLUDE_CONFIG
    cc -c  volumeLinear.c -DINCLUDE_CONFIG
    cc -c  volumeLog.c -DINCLUDE_CONFIG
    cc -c  interfaces.c -DINCLUDE_CONFIG
    cc -c  processData.c -DINCLUDE_CONFIG
    cc -c  processAscii.c -DINCLUDE_CONFIG
    cc -c  processNumeric.c -DINCLUDE_CONFIG
    cc -c  verifyConfig.c -DINCLUDE_CONFIG
    cc -c  mixerAlsa.c -DINCLUDE_CONFIG
    mixerAlsa.c: In Funktion »initMixer«:
    mixerAlsa.c:57:5: Warnung: Implizite Deklaration der Funktion »validateConfigBool« [-Wimplicit-function-declaration]
       57 |     validateConfigBool(&config, "mixer_normalize", &volumeNormalized, 0);
          |     ^~~~~~~~~~~~~~~~~~
    cc -c  smoothVolume.c -DINCLUDE_CONFIG
    smoothVolume.c: In Funktion »init«:
    smoothVolume.c:113:9: Warnung: Implizite Deklaration der Funktion »validateConfigInt« [-Wimplicit-function-declaration]
      113 |         validateConfigInt(&config, "volume.mutation", &tempInt, -1, 1, 1000, 100);
          |         ^~~~~~~~~~~~~~~~~
    cc -c  mods.c -DINCLUDE_CONFIG
    cc -c  modVolumeResponseRange.c -DINCLUDE_CONFIG
    cc -c  modVolumeResponseCondResize.c -DINCLUDE_CONFIG
    modVolumeResponseCondResize.c: In Funktion »init«:
    modVolumeResponseCondResize.c:54:12: Warnung: Implizite Deklaration der Funktion »strcmp« [-Wimplicit-function-declaration]
       54 |         if(strcmp(type, "lower_limit"))
          |            ^~~~~~
    cc -c  modCommandDynaudio.c -DINCLUDE_CONFIG
    modCommandDynaudio.c: In Funktion »init«:
    modCommandDynaudio.c:54:8: Warnung: Implizite Deklaration der Funktion »strcmp« [-Wimplicit-function-declaration]
       54 |     if(strcmp(common_data.process->name, "numeric") != 0) {
          |        ^~~~~~
    cc -c  modCommandDenonAVR.c -DINCLUDE_CONFIG
    modCommandDenonAVR.c: In Funktion »init«:
    modCommandDenonAVR.c:51:8: Warnung: Implizite Deklaration der Funktion »strcmp« [-Wimplicit-function-declaration]
       51 |     if(strcmp(common_data.process->name, "ascii") != 0) {
          |        ^~~~~~
    cc -c  volume_mapping.c -DINCLUDE_CONFIG
    cc -c  interfaceSerial.c -DINCLUDE_CONFIG
    interfaceSerial.c: In Funktion »init«:
    interfaceSerial.c:76:83: Warnung: Implizite Deklaration der Funktion »strerror«; meinten Sie »perror«? [-Wimplicit-function-declaration]
       76 |         syslog(LOG_ERR, "Failed to open serial device %s: %s (%i)", serialDevice, strerror(errno), errno);
          |                                                                                   ^~~~~~~~
          |                                                                                   perror
    cc -c  messageQueue.c -DINCLUDE_CONFIG
    cc -o synchronator synchronator.o volume.o volumeLinear.o volumeLog.o interfaces.o processData.o processAscii.o processNumeric.o verifyConfig.o mixerAlsa.o smoothVolume.o mods.o modVolumeResponseRange.o modVolumeResponseCondResize.o modCommandDynaudio.o modCommandDenonAVR.o volume_mapping.o interfaceSerial.o messageQueue.o -lpthread -lm -lasound  -lconfig
    /usr/bin/ld: volume.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: volume.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: volumeLinear.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: volumeLinear.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: volumeLog.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: volumeLog.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: processData.o:(.data.rel.local+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: processData.o:(.bss+0x0): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: processAscii.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: processAscii.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: processNumeric.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: processNumeric.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: mixerAlsa.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: mixerAlsa.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: smoothVolume.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: smoothVolume.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: mods.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: mods.o:(.data.rel.local+0x0): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: modVolumeResponseRange.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: modVolumeResponseRange.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: modVolumeResponseCondResize.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: modVolumeResponseCondResize.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: modCommandDynaudio.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: modCommandDynaudio.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: modCommandDenonAVR.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: modCommandDenonAVR.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: interfaceSerial.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: interfaceSerial.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    /usr/bin/ld: messageQueue.o:(.bss+0x0): multiple definition of `statusInfo'; synchronator.o:(.bss+0x0): first defined here
    /usr/bin/ld: messageQueue.o:(.bss+0x18): multiple definition of `mod'; synchronator.o:(.bss+0x18): first defined here
    collect2: Fehler: ld gab 1 als Ende-Status zurück
    make: *** [Makefile:76: synchronator] Fehler 1

**Comment by therealmuffin** [comment] 2020-11-11 18:58
Interesting. I've tried the latest Debian stable release and I can reproduce the compilation warnings. I've pushed a fix for that. I've also updated the documentation (actually, I had already done that some time ago, but forgot to push it to Github).

Unfortunately, I can't reproduce the compilation errors you're experiencing. Can you tell me what compiler you're using (make -v)?

**Comment by straw-son** [comment] 2020-11-12 10:51
Probably a more recent version compared to Debian:

    [user@pi4 ~]$ make -v
    GNU Make 4.3
    Built for aarch64-unknown-linux-gnu
    Copyright (C) 1988-2020 Free Software Foundation, Inc.

    [user@pi4 ~]$ cc -v
    Using built-in specs.
    COLLECT_GCC=cc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-unknown-linux-gnu/10.2.0/lto-wrapper
    Target: aarch64-unknown-linux-gnu
    Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --enable-languages=c,c++,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-multilib --disable-werror --host=aarch64-unknown-linux-gnu --build=aarch64-unknown-linux-gnu --with-arch=armv8-a --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419 gdc_include_dir=/usr/include/dlang/gdc
    Thread model: posix
    Supported LTO compression algorithms: zlib zstd
    gcc version 10.2.0 (GCC)

    [user@pi4 ~]$ ld -v
    GNU ld (GNU Binutils) 2.35

**Comment by therealmuffin** [comment] 2020-11-12 19:47
I've been able to reproduce this issue in Debian Bullseye which includes make 4.3/gcc 10.2.0. It appears I've improperly declared some variables (defined actually). This should now be fixed.

I'll close this issue. Please reopen if the issue persists.

**Closed as completed by therealmuffin** 2020-11-12 19:47 UTC
