### ISSUE TITLE
Dynaudio Connect: speakers stay standby for a long time

### ISSUE THREAD

**Issue by jnorbi** [therealmuffin/synchronator#4] opened 2016-10-18 22:02 UTC
Hi,

Minor issue: while the service is running the speakers stay in standby mode for a very long time (minutes) after I stop/pause the music on the source. Without the synchronator service the speakers stay in standy mode for seconds and after turns itself off. Maybe connecting issue that sometimes the daemon can't connect to the Dynaudio Connect with the following error message: "Failed to connect socket"; is there everything correct around the connection handling? Only solution for that is restarting the Dynaudio Connect box.

Thanks in advance,
Norbert

**Comment by therealmuffin** [comment] 2016-10-19 14:17
It seems Synchronator sometimes can't connect to your Dynaudio Connect. This could be caused by a network problem or if the Connect is unresponsive, possibly the Dynaudio Connect Control app is already connected to the Connect? The Connect allows only one connection at a time (last time I checked). I could keep Synchronator in a loop until it is connected. That would reduce error checking (wrong IP) but it would make the system more robust. I'll see if I can add an option for that.
- To check for certain if it is Synchronator related, you can check with telnet. If that doesn't connect, the Connect is simply unreachable (most likely scenario): telnet IP_ADDRESS 1901

As for the standby issue, as far as I'm aware, as long as nothing is touched, Synchronator should not send out anything (e.g. volume mutation internally initiated). Unless of course the connection to the Connect itself keeps the speakers from switching to standby.

A couple of questions?
- Can you confirm in the log output that Synchronator is not sending out any data to the speakers (volume/other options)?
- If not, could you check if keeping the Dynaudio Connect Control app open has the same effect? I believe the speakers should go into standby after 20 minutes without an audio input.

Kind regards, Maarten

**Comment by jnorbi** [comment] 2016-10-19 21:16
Before I opened this ticket I just tried and figured out something:
- while the Synchronator can't connect the Dynaudio Connect I can ping it from the same computer
- yes, I deleted the app from my phone to exclude the possibility of the app connection
- once Synchronator connected then the connection is rock solid, without break(s)

I think it's a good idea to put a loop with a counter (max. 5-10 tries), and after 'n' failure you can do the same like now > timeout. Between the tires the Syncronator should sleep a bit, like 2-3 seconds. Is that a robust thing?

At the moment I can't create the situation like yesterday, now it can connect on every run...

Answers to your questions:
- what I can see in the log when the music paused/stopped is the "Leftovers in buffer (bytes read, #leftovers)" like messages, these messages are continuously coming - 2 log entries in every 2-4 seconds until the speakers are not in standby mode
- it's a Xeo 4, and without Syncronator it goes from blinking standby to complete standby in ~3 minutes, when the Syncronator is up and running in ~5 minutes, when the app is connected in ~5 minutes

So okay, we can say that it's normal when TCP session opened. A bit longer time, but seems okay.

PS: I found a volume level control issue, I'll make video about it and open a new issue (when the volume level in alsa is between 70-90 nothing happens on Dynaudio speakers). I think you can close this ticket, maybe once you will implement the retries for the connection. Thanks for that great tool!

Regards,
Norbert

**Comment by therealmuffin** [comment] 2016-10-23 11:37
Ok, I can't reproduce the connection problem. Since your solution was restarting the Connect I will assume that either the Connect was a bit confused or there was already another connection active. If Synchronator can't connect again but you can login via telnet (telnet IP_ADDRESS 1901), please create an issue for it.

As for the standby issue, that seems to be solved so I will close this issue. I will make the tcp (re)connection a bit more robust, should get that done in a couple of weeks.

As for the volume level issue in the range 70-90, can't reproduce that either. If that still happens, please create a new issue for it.

Kind regards, Maarten

**Closed as completed by therealmuffin** 2016-10-23 11:37 UTC
